packages:
  - 'packages/*'
  - playground

catalog:
  '@volar/language-core': ^2.4.20
  '@volar/language-server': ^2.4.20
  '@volar/typescript': ^2.4.20
  '@volar/vscode': ^2.4.20
  typescript: ^5.8.3
  vscode-uri: ^3.1.0

patchedDependencies:
  "@volar/typescript": "patches/@volar__typescript.patch"
