packages:
  - 'packages/*'
  - playground

catalog:
  '@volar/language-core': ^2.4.17
  '@volar/language-server': ^2.4.17
  '@volar/typescript': ^2.4.17
  '@volar/vscode': ^2.4.17
  typescript: ^5.8.3
  vscode-uri: ^3.1.0
