packages:
  - 'packages/*'
  - playground

catalog:
  '@volar/language-core': ^2.4.13
  '@volar/language-server': ^2.4.13
  '@volar/typescript': ^2.4.13
  '@volar/vscode': ^2.4.13
  typescript: ^5.7.2
  rollup-utils: ^0.0.3
  vscode-uri: ^3.0.8
