packages:
  - 'packages/*'
  - playground

catalog:
  '@volar/language-core': ^2.4.23
  '@volar/language-server': ^2.4.23
  '@volar/typescript': ^2.4.23
  '@volar/vscode': ^2.4.23
  typescript: ^5.9.2
  vscode-uri: ^3.1.0
