name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        run: pnpm publish --filter="!vscode-ts-macro" --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Publish to VSCode
        run: pnpm run --filter="vscode-ts-macro" release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
